### ISSUE TITLE
Connect the Geofencing Api to LOST's location mocking

### ISSUE THREAD

**Issue by Grsmto** [lostzen/lost#212]
### Description
Connecting the GeofencingApi to LOST's location mocking was on a checklist of [this PR](https://github.com/mapzen/LOST/pull/91#issuecomment-245062973) but seemed to get lost (lol) in the wild. 

Question: how do you test in development that the geofences are working? Is there any way to do this if the mock currently doesn't support it?

Thanks!

**Comment by msmollin** [comment]
Thanks for the question @Grsmto, and thanks for pointing out that that feature fell between the cracks. We have not had a lot of call for geofence support until recently so it's been one of those features that has been de-prioritized behind other features, and when we were testing it, it was mostly manual as I recall (it's been some time). We should however get this hooked up to help with testing.

Since we just got done a development cycle on LOST for the 3.0 release, we're working on upgrading our other in-house dependencies to support the new LOST infrastructure and API. Once that all settles down, we'll work on prioritizing this. Feel free to start on the work if you have need of it sooner. We can always provide feedback and guidance until we can swing back around!

**Comment by msmollin** [comment]
Closing as this repo is no longer maintained.
