### ISSUE TITLE
Better GPS Fix

### ISSUE THREAD

**Issue by Mannshoch** [lostzen/lost#254]
### Description
At moment i have to pick a random destination in my Navigation App (Osmand) so this app runs in background. Otherwise I'm not able to get a GPS Fix.

Fairphone 2
Android 6.0.1

See also -->  https://github.com/westnordost/StreetComplete/issues/743

**Comment by westnordost** [comment]
Just a comment on the side:

I think the reason why smartphones nowadays get a GPS fix so quickly is because Google does not only use [Assisted GPS](https://en.wikipedia.org/wiki/Assisted_GPS) with cell towers but use [Wi-Fi positioning](https://en.wikipedia.org/wiki/Wi-Fi_positioning_system). Google is not mentioned in the latter linked article, but I guess it is even the largest database.

Point is, that I don't know if the Android system automatically uses Google's wi-fi positioning (if mobile data and wifi is on) or if this is only done if using _Google Play services location APIs_. My suspicion is that is must be something like that if one app can retrieve the position "better" than another, even though both apps are allegedly just asking the Android system for the position.

Perhaps anyone working on LOST has had more insight into this?

**Comment by msmollin** [comment]
That is correct @westnordost  - If you're using the fused location services from Google Play, it uses Wifi, cellular, and Bluetooth-based (from their beacon implementation) location services as well as GPS. LOST at the moment only provides GPS connectivity however it has come up a few times now in other tickets an interest in having additional options. 

Cellular would likely be the next one to work on as it does not require any hosted data like wifi databases. However we haven't looked into the topic further than "this would be cool", so we have no idea if AOSP even provides the API access to the hardware we'd need to make it happen.

**Comment by Mannshoch** [comment]
I have no Google Play service installed but [unifiedNlp](https://f-droid.org/packages/com.google.android.gms/) only with the add-on [LocalGsmNlpBackend](https://f-droid.org/de/packages/org.fitchfamily.android.gsmlocation/) is available.

Strange is, that I also in Osmand another App is needed to get a faster GPS Fix. In Osmand the Problem is I have immediately a GSM Fix, but in that second I activate GPS Osmand lost its GSM Fix and I have to wait a long time. If in background Mozilla Stumbler is running every thing is fine and also a fast GPS fix is available.

**Comment by msmollin** [comment]
Closing as this repo is no longer maintained.
