### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by tananaev** [lostzen/lost#264]
Is this project dead? Broken links everywhere, no new updates. Are there any alternatives?

**Comment by msmollin** [comment]
Hello @tananaev dead is a little extreme. Dormant is probably a better word. We're still here and answering issues, but we're currently lacking time to re-apply ourselves to fixing issues since Mapzen shut down. 

I'm unaware of any alternatives although @sarahlensing / @ecgreb might have some better ideas.

**Comment by ecgreb** [comment]
I'm not aware of any alternatives either and also have not had dedicate time to devote to this project since transitioning to a new role.

@tananaev are there specific issues you are running into we can help with? I see the link to Circle CI is currently broken due to the Mapzen org going away. That should be an easy fix. Any others you found?

**Comment by tananaev** [comment]
We use Crashlytics and we get quite a few crashes related to Lost library. The most common is #261.

Issues is one thing, but I'm also trying to assess long term strategy. Google Services library has changed quite a bit, so Lost is longer just a drop-in 1 to 1 replacement. It seems to be stuck in the past and not actively supported anymore.

**Comment by nvkelso** [comment]
@tananaev If you find Lost useful please consider putting some development effort towards this open source community project. PRs are welcome :)

**Comment by tananaev** [comment]
I know, but I have too many open source projects of my own. Don't have enough time to contribute to this one. Just wanted to confirm the state of this project.

**Comment by oliv3** [comment]
@ecgreb @nvkelso https://github.com/lostzen/lost/issues/261 is updated with a case to reproduce, if this can help.

**Comment by msmollin** [comment]
Closing as this repo is no longer maintained.
